### ISSUE TITLE
Make `check` argument available

### ISSUE THREAD

**Issue by jenstroeger** [commitizen-tools/commitizen-action#9]
A bit of inspiration from [CondeNast/conventional-pull-request-action](https://github.com/CondeNast/conventional-pull-request-action)

It looks like this current action runs `version` then `bump` only. Would it be possible to add `check` as well, to use this action to verify PR titles like the above action?

<hr>

And also just to be sure, it looks to me like this `commitizen-action` is very similar/the same as [relekang/python-semantic-release](https://github.com/relekang/python-semantic-release)?

**Comment by nbrugger-tgm** [comment]
> And also just to be sure, it looks to me like this `commitizen-action` is very similar/the same as [relekang/python-semantic-release](https://github.com/relekang/python-semantic-release)?

To be honest this is kind of wrong. `commitizen` is a tool as well as `semantic-release`. While yes both tools provide very similar functionality they are definetly not the same. If you use the co,mitizen cli tool locally and use their format you want to use this action.

It is the same as if you say "also just to be sure, to me it looks like this `gradle-build` action is very similar/the same as `maven-build`

**Comment by nbrugger-tgm** [comment]
> It looks like this current action runs `version` then `bump` only. Would it be possible to add `check` as well, to use this action to verify PR titles like the above action?

The commitizen tool is not a linter, while it can verify conventional commit messages thats not the scope of this tool/action.

This action is to execute the cli tool on the CI/CD. Therefore creating a release/bumping the version. But the tool inheritly takes the version information from the commit history (which they do lint) and not from the PR title. In the end of the day this action is just a wrapper for the cli tool.

But there are other options to do what you stave for. There are many actions out there that check if the title is conventional-commit friendly, altho i am quite sure you already found that out.


Just as a disclosure, i am not a contributor of commitizen, just a user of the tool. But i am quite sure you could close the issue since your requirements are not inline with the target of this action.

**Comment by Woile** [comment]
As @nbrugger-tgm commented, `check` is out of scope. I think the best would be to create another github action which would run the `cz check`.
